# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfinance.proto\"\x1f\n\rTickerRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\"\xb7\x02\n\x0eTickerResponse\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61yHigh\x18\x03 \x01(\x02\x12\x0e\n\x06\x64\x61yLow\x18\x04 \x01(\x02\x12\x17\n\x0f\x66iftyDayAverage\x18\x05 \x01(\x02\x12\x11\n\tlastPrice\x18\x06 \x01(\x02\x12\x12\n\nlastVolume\x18\x07 \x01(\x02\x12\x11\n\tmarketCap\x18\x08 \x01(\x02\x12\x0c\n\x04open\x18\t \x01(\x02\x12\x15\n\rpreviousClose\x18\n \x01(\x02\x12\x11\n\tquoteType\x18\x0b \x01(\t\x12\x0e\n\x06shares\x18\x0c \x01(\x03\x12\x10\n\x08timezone\x18\r \x01(\t\x12\x12\n\nyearChange\x18\x0e \x01(\x02\x12\x10\n\x08yearHigh\x18\x0f \x01(\x02\x12\x0f\n\x07yearLow\x18\x10 \x01(\x02\":\n\x0fTickersResponse\x12\'\n\x0etickerResponse\x18\x01 \x03(\x0b\x32\x0f.TickerResponse\"y\n\x04News\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tpublisher\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\x1b\n\x13providerPublishTime\x18\x04 \x01(\x05\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x16\n\x0erelatedTickers\x18\x06 \x03(\t\"#\n\x0cNewsResponse\x12\x13\n\x04news\x18\x07 \x03(\x0b\x32\x05.News2\xb0\x01\n\x07\x46inance\x12\x37\n\x12GetFinanceResponse\x12\x0e.TickerRequest\x1a\x0f.TickerResponse\"\x00\x12\x32\n\x0fGetNewsResponse\x12\x0e.TickerRequest\x1a\r.NewsResponse\"\x00\x12\x38\n\x12GetTickersResponse\x12\x0e.TickerRequest\x1a\x10.TickersResponse\"\x00\x62\x06proto3')



_TICKERREQUEST = DESCRIPTOR.message_types_by_name['TickerRequest']
_TICKERRESPONSE = DESCRIPTOR.message_types_by_name['TickerResponse']
_TICKERSRESPONSE = DESCRIPTOR.message_types_by_name['TickersResponse']
_NEWS = DESCRIPTOR.message_types_by_name['News']
_NEWSRESPONSE = DESCRIPTOR.message_types_by_name['NewsResponse']
TickerRequest = _reflection.GeneratedProtocolMessageType('TickerRequest', (_message.Message,), {
  'DESCRIPTOR' : _TICKERREQUEST,
  '__module__' : 'finance_pb2'
  # @@protoc_insertion_point(class_scope:TickerRequest)
  })
_sym_db.RegisterMessage(TickerRequest)

TickerResponse = _reflection.GeneratedProtocolMessageType('TickerResponse', (_message.Message,), {
  'DESCRIPTOR' : _TICKERRESPONSE,
  '__module__' : 'finance_pb2'
  # @@protoc_insertion_point(class_scope:TickerResponse)
  })
_sym_db.RegisterMessage(TickerResponse)

TickersResponse = _reflection.GeneratedProtocolMessageType('TickersResponse', (_message.Message,), {
  'DESCRIPTOR' : _TICKERSRESPONSE,
  '__module__' : 'finance_pb2'
  # @@protoc_insertion_point(class_scope:TickersResponse)
  })
_sym_db.RegisterMessage(TickersResponse)

News = _reflection.GeneratedProtocolMessageType('News', (_message.Message,), {
  'DESCRIPTOR' : _NEWS,
  '__module__' : 'finance_pb2'
  # @@protoc_insertion_point(class_scope:News)
  })
_sym_db.RegisterMessage(News)

NewsResponse = _reflection.GeneratedProtocolMessageType('NewsResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWSRESPONSE,
  '__module__' : 'finance_pb2'
  # @@protoc_insertion_point(class_scope:NewsResponse)
  })
_sym_db.RegisterMessage(NewsResponse)

_FINANCE = DESCRIPTOR.services_by_name['Finance']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TICKERREQUEST._serialized_start=17
  _TICKERREQUEST._serialized_end=48
  _TICKERRESPONSE._serialized_start=51
  _TICKERRESPONSE._serialized_end=362
  _TICKERSRESPONSE._serialized_start=364
  _TICKERSRESPONSE._serialized_end=422
  _NEWS._serialized_start=424
  _NEWS._serialized_end=545
  _NEWSRESPONSE._serialized_start=547
  _NEWSRESPONSE._serialized_end=582
  _FINANCE._serialized_start=585
  _FINANCE._serialized_end=761
# @@protoc_insertion_point(module_scope)
