# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import financial_statement_pb2 as financial__statement__pb2


class FinancialStatementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFinancialStatement = channel.unary_unary(
                '/FinancialStatement/GetFinancialStatement',
                request_serializer=financial__statement__pb2.FinancialStatementRequest.SerializeToString,
                response_deserializer=financial__statement__pb2.FinancialStatementResponse.FromString,
                )


class FinancialStatementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFinancialStatement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinancialStatementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFinancialStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinancialStatement,
                    request_deserializer=financial__statement__pb2.FinancialStatementRequest.FromString,
                    response_serializer=financial__statement__pb2.FinancialStatementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FinancialStatement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FinancialStatement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFinancialStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FinancialStatement/GetFinancialStatement',
            financial__statement__pb2.FinancialStatementRequest.SerializeToString,
            financial__statement__pb2.FinancialStatementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
