# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: financial_statement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66inancial_statement.proto\"b\n\x19\x46inancialStatementRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12&\n\x0cpdf_response\x18\x03 \x01(\x0e\x32\x10.TypePDFResponse\"X\n\x1a\x46inancialStatementResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0b\n\x03pdf\x18\x02 \x01(\x0c\x12\x0c\n\x04year\x18\x03 \x01(\t\x12\x0f\n\x07pdf_url\x18\x04 \x01(\t*-\n\x0fTypePDFResponse\x12\x0b\n\x07PDF_URL\x10\x00\x12\r\n\tPDF_BYTES\x10\x01\x32h\n\x12\x46inancialStatement\x12R\n\x15GetFinancialStatement\x12\x1a.FinancialStatementRequest\x1a\x1b.FinancialStatementResponse\"\x00\x62\x06proto3')

_TYPEPDFRESPONSE = DESCRIPTOR.enum_types_by_name['TypePDFResponse']
TypePDFResponse = enum_type_wrapper.EnumTypeWrapper(_TYPEPDFRESPONSE)
PDF_URL = 0
PDF_BYTES = 1


_FINANCIALSTATEMENTREQUEST = DESCRIPTOR.message_types_by_name['FinancialStatementRequest']
_FINANCIALSTATEMENTRESPONSE = DESCRIPTOR.message_types_by_name['FinancialStatementResponse']
FinancialStatementRequest = _reflection.GeneratedProtocolMessageType('FinancialStatementRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINANCIALSTATEMENTREQUEST,
  '__module__' : 'financial_statement_pb2'
  # @@protoc_insertion_point(class_scope:FinancialStatementRequest)
  })
_sym_db.RegisterMessage(FinancialStatementRequest)

FinancialStatementResponse = _reflection.GeneratedProtocolMessageType('FinancialStatementResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINANCIALSTATEMENTRESPONSE,
  '__module__' : 'financial_statement_pb2'
  # @@protoc_insertion_point(class_scope:FinancialStatementResponse)
  })
_sym_db.RegisterMessage(FinancialStatementResponse)

_FINANCIALSTATEMENT = DESCRIPTOR.services_by_name['FinancialStatement']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPEPDFRESPONSE._serialized_start=219
  _TYPEPDFRESPONSE._serialized_end=264
  _FINANCIALSTATEMENTREQUEST._serialized_start=29
  _FINANCIALSTATEMENTREQUEST._serialized_end=127
  _FINANCIALSTATEMENTRESPONSE._serialized_start=129
  _FINANCIALSTATEMENTRESPONSE._serialized_end=217
  _FINANCIALSTATEMENT._serialized_start=266
  _FINANCIALSTATEMENT._serialized_end=370
# @@protoc_insertion_point(module_scope)
